on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Run markdown link checker
      uses: gaurav-nelson/github-action-markdown-link-check@0fe4911067fa322422f325b002d2038ba5602170
      with:
        config-file: '.github/workflows/markdown.links.config.json'
        folder-path: '.'
